DEFAULT_MODE = "live"
DEFAULT_REFRESH_MS = 250
DEFAULT_STRESS_WORKERS = 8
DEFAULT_STRESS_DURATION_MS = 5000

WINDOW_TITLE = "TheOS PerfKit WM"
WINDOW_WIDTH = 1040
WINDOW_HEIGHT = 700
WINDOW_X = 80
WINDOW_Y = 52
