function(theos_install_headers target_name)
    file(GLOB_RECURSE headers RELATIVE ${CMAKE_SOURCE_DIR}/Includes/${traget_name} "*.h")
    foreach(header ${headers})
        get_filename_component(subdirectory ${header} DIRECTORY)
        install(FILES ${header} DESTINATION usr/include/${target_name}/${subdirectory})
    endforeach()
endfunction()

function(theos_install_sources target_name)
    file(GLOB_RECURSE sources RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} "*.h" "*.c")
    foreach(source ${sources})
        get_filename_component(subdirectory ${source} DIRECTORY)
        install(FILES ${source} DESTINATION usr/src/theos/${target_name}/${subdirectory})
    endforeach()
endfunction()